-- ============================================================
-- VISION-MSSQL Upgrade Script: Version 8.6 -> 9.0.2 (Part 2a)
-- Target:  SQL Server (T-SQL / MSSQL)
-- Type:    Idempotent - safe to run multiple times
-- Module:  NoVLS (No Virtual Learning Schedule)
-- ============================================================

Print '*** Updating and Combining the Approved status for Objsctives ***'
go

-- ============================================================
-- SECTION 1: Default Constraint Drops / Re-Adds
-- ============================================================

Print '*** Section 1: Recreating default constraints ***'
go

-- APP_VERSION.DATE_MODIFIED
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_APP_VERSION_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.APP_VERSION DROP CONSTRAINT DF_APP_VERSION_DATE_MODIFIED;
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_APP_VERSION_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.APP_VERSION ADD CONSTRAINT DF_APP_VERSION_DATE_MODIFIED DEFAULT GETDATE() FOR DATE_MODIFIED;
GO

-- DB_UPDATE_HISTORY.DATE_APPLIED
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_DB_UPDATE_HISTORY_DATE_APPLIED' AND type = 'D')
    ALTER TABLE dbo.DB_UPDATE_HISTORY DROP CONSTRAINT DF_DB_UPDATE_HISTORY_DATE_APPLIED;
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_DB_UPDATE_HISTORY_DATE_APPLIED' AND type = 'D')
    ALTER TABLE dbo.DB_UPDATE_HISTORY ADD CONSTRAINT DF_DB_UPDATE_HISTORY_DATE_APPLIED DEFAULT GETDATE() FOR DATE_APPLIED;
GO

-- EXAM_LEARNER_FEEDBACK.DATE_MODIFIED
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_EXAM_LEARNER_FEEDBACK_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.EXAM_LEARNER_FEEDBACK DROP CONSTRAINT DF_EXAM_LEARNER_FEEDBACK_DATE_MODIFIED;
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_EXAM_LEARNER_FEEDBACK_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.EXAM_LEARNER_FEEDBACK ADD CONSTRAINT DF_EXAM_LEARNER_FEEDBACK_DATE_MODIFIED DEFAULT GETDATE() FOR DATE_MODIFIED;
GO

-- EXAM_QUESTION_EVENT.DATE_MODIFIED
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_EXAM_QUESTION_EVENT_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.EXAM_QUESTION_EVENT DROP CONSTRAINT DF_EXAM_QUESTION_EVENT_DATE_MODIFIED;
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_EXAM_QUESTION_EVENT_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.EXAM_QUESTION_EVENT ADD CONSTRAINT DF_EXAM_QUESTION_EVENT_DATE_MODIFIED DEFAULT GETDATE() FOR DATE_MODIFIED;
GO

-- LABEL.DATE_MODIFIED
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_LABEL_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.LABEL DROP CONSTRAINT DF_LABEL_DATE_MODIFIED;
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_LABEL_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.LABEL ADD CONSTRAINT DF_LABEL_DATE_MODIFIED DEFAULT GETDATE() FOR DATE_MODIFIED;
GO

-- LEARNER.DATE_MODIFIED
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_LEARNER_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.LEARNER DROP CONSTRAINT DF_LEARNER_DATE_MODIFIED;
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_LEARNER_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.LEARNER ADD CONSTRAINT DF_LEARNER_DATE_MODIFIED DEFAULT GETDATE() FOR DATE_MODIFIED;
GO

-- RECYCLED.DATE_MODIFIED
IF EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_RECYCLED_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.RECYCLED DROP CONSTRAINT DF_RECYCLED_DATE_MODIFIED;
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_RECYCLED_DATE_MODIFIED' AND type = 'D')
    ALTER TABLE dbo.RECYCLED ADD CONSTRAINT DF_RECYCLED_DATE_MODIFIED DEFAULT GETDATE() FOR DATE_MODIFIED;
GO

-- ============================================================
-- SECTION 2: PROGRAM_STATIC_EXAM default constraint rename
-- ============================================================

Print '*** Section 2: Renaming PROGRAM_STATIC_EXAM default constraint ***'
go

IF NOT EXISTS (SELECT * FROM sys.objects WHERE name = 'DF_PROG_STATIC_EXAM_USED_IN_LS' AND type = 'D')
BEGIN
    DECLARE @ConstraintName NVARCHAR(200);
    SELECT @ConstraintName = dc.name
    FROM sys.default_constraints dc
    JOIN sys.columns c ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id
    JOIN sys.tables t ON c.object_id = t.object_id
    WHERE t.name = 'PROGRAM_STATIC_EXAM' AND c.name = 'USED_IN_LS';

    IF @ConstraintName IS NOT NULL
        EXEC sp_rename @ConstraintName, 'DF_PROG_STATIC_EXAM_USED_IN_LS', 'OBJECT';
END
GO

-- ============================================================
-- SECTION 3: EXAM_QUESTION_EVENT FK drop + column change to NOT NULL
-- ============================================================

Print '*** Section 3: EXAM_QUESTION_EVENT FK drop and column nullability change ***'
go

-- Drop FK so we can alter the column
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
           WHERE CONSTRAINT_NAME = 'FK_EXAM_QUESTION_EVENT_IMPL_ID' AND TABLE_NAME = 'EXAM_QUESTION_EVENT')
    ALTER TABLE dbo.EXAM_QUESTION_EVENT DROP CONSTRAINT FK_EXAM_QUESTION_EVENT_IMPL_ID;
GO

-- Ensure no NULLs exist before making the column NOT NULL
UPDATE dbo.EXAM_QUESTION_EVENT
SET FK_QUESTION_IMPL = 0
WHERE FK_QUESTION_IMPL IS NULL;
GO

ALTER TABLE dbo.EXAM_QUESTION_EVENT ALTER COLUMN FK_QUESTION_IMPL NUMERIC(12, 0) NOT NULL;
GO

-- ============================================================
-- SECTION 4: EXAM_QUESTION_EVENT PK recreation
-- ============================================================

Print '*** Section 4: EXAM_QUESTION_EVENT PK recreation ***'
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
           WHERE CONSTRAINT_NAME = 'PK_EXAM_QUESTION_EVENT' AND TABLE_NAME = 'EXAM_QUESTION_EVENT')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT] DROP CONSTRAINT [PK_EXAM_QUESTION_EVENT];
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'PK_EXAM_QUESTION_EVENT' AND TABLE_NAME = 'EXAM_QUESTION_EVENT')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT] WITH NOCHECK ADD CONSTRAINT [PK_EXAM_QUESTION_EVENT]
    PRIMARY KEY CLUSTERED ([PK_EXAM_QUESTION_EVENT_ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
          IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

-- ============================================================
-- SECTION 5: EXAM_QUESTION_EVENT_MC FK drop + column change + temp indexes
-- ============================================================

Print '*** Section 5: EXAM_QUESTION_EVENT_MC operations ***'
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
           WHERE CONSTRAINT_NAME = 'FK_EXAM_QUESTION_EVENT_MC_IMPL' AND TABLE_NAME = 'EXAM_QUESTION_EVENT_MC')
    ALTER TABLE dbo.EXAM_QUESTION_EVENT_MC DROP CONSTRAINT FK_EXAM_QUESTION_EVENT_MC_IMPL;
GO

UPDATE dbo.EXAM_QUESTION_EVENT_MC
SET FK_QUESTION_IMPL = 0
WHERE FK_QUESTION_IMPL IS NULL;
GO

ALTER TABLE dbo.EXAM_QUESTION_EVENT_MC ALTER COLUMN FK_QUESTION_IMPL NUMERIC(12, 0) NOT NULL;
GO

-- Temp indexes to support data migration performance
IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.EXAM_QUESTION_EVENT_MC') AND name = 'EXAM_QUESTION_EVENT_MC_TEMP1')
    CREATE NONCLUSTERED INDEX [EXAM_QUESTION_EVENT_MC_TEMP1]
    ON [dbo].[EXAM_QUESTION_EVENT_MC] ([FK_EXAM_ID] ASC, [FK_QUESTION_IMPL] ASC);
GO

IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.EXAM_QUESTION_EVENT_MC') AND name = 'EXAM_QUESTION_EVENT_MC_TEMP2')
    CREATE NONCLUSTERED INDEX [EXAM_QUESTION_EVENT_MC_TEMP2]
    ON [dbo].[EXAM_QUESTION_EVENT_MC] ([FK_QUESTION_IMPL] ASC);
GO

-- ============================================================
-- SECTION 6: EXAM_QUESTION_EVENT_MA FK drop + column change + temp indexes
-- ============================================================

Print '*** Section 6: EXAM_QUESTION_EVENT_MA operations ***'
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
           WHERE CONSTRAINT_NAME = 'FK_EXAM_QUESTION_EVENT_MA_IMPL' AND TABLE_NAME = 'EXAM_QUESTION_EVENT_MA')
    ALTER TABLE dbo.EXAM_QUESTION_EVENT_MA DROP CONSTRAINT FK_EXAM_QUESTION_EVENT_MA_IMPL;
GO

UPDATE dbo.EXAM_QUESTION_EVENT_MA
SET FK_QUESTION_IMPL = 0
WHERE FK_QUESTION_IMPL IS NULL;
GO

ALTER TABLE dbo.EXAM_QUESTION_EVENT_MA ALTER COLUMN FK_QUESTION_IMPL NUMERIC(12, 0) NOT NULL;
GO

IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.EXAM_QUESTION_EVENT_MA') AND name = 'EXAM_QUESTION_EVENT_MA_TEMP1')
    CREATE NONCLUSTERED INDEX [EXAM_QUESTION_EVENT_MA_TEMP1]
    ON [dbo].[EXAM_QUESTION_EVENT_MA] ([FK_EXAM_ID] ASC, [FK_QUESTION_IMPL] ASC);
GO

IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.EXAM_QUESTION_EVENT_MA') AND name = 'EXAM_QUESTION_EVENT_MA_TEMP2')
    CREATE NONCLUSTERED INDEX [EXAM_QUESTION_EVENT_MA_TEMP2]
    ON [dbo].[EXAM_QUESTION_EVENT_MA] ([FK_QUESTION_IMPL] ASC);
GO

-- ============================================================
-- SECTION 7: Data migration - Combining Approved status for Objectives
-- ============================================================

Print '*** Section 7: Propagating APPROVED_STATUS from OBJECTIVE to OBJECTIVE_IMPL ***'
go

DECLARE @PK_OBJ_ID NUMERIC(12,0)
DECLARE @STATUS INT

DECLARE OBJ_CURSOR CURSOR FOR
    SELECT PK_OBJ_ID, APPROVED_STATUS
    FROM dbo.OBJECTIVE
    WHERE APPROVED_STATUS IS NOT NULL

OPEN OBJ_CURSOR
FETCH NEXT FROM OBJ_CURSOR INTO @PK_OBJ_ID, @STATUS

WHILE @@FETCH_STATUS = 0
BEGIN
    UPDATE dbo.OBJECTIVE_IMPL
    SET APPROVED_STATUS = @STATUS
    WHERE FK_OBJ_ID = @PK_OBJ_ID

    FETCH NEXT FROM OBJ_CURSOR INTO @PK_OBJ_ID, @STATUS
END

CLOSE OBJ_CURSOR
DEALLOCATE OBJ_CURSOR
go

-- ============================================================
-- SECTION 8: QUAL_CARD_IMPL NULL-safe UPDATE statements
-- ============================================================

Print '*** Section 8: QUAL_CARD_IMPL default value backfill ***'
go

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'QUAL_CARD_IMPL' AND COLUMN_NAME = 'FK_ORG_INFO')
BEGIN
    UPDATE dbo.QUAL_CARD_IMPL SET FK_ORG_INFO = 1 WHERE FK_ORG_INFO IS NULL;
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'QUAL_CARD_IMPL' AND COLUMN_NAME = 'ROUTE_SUPERVISOR')
BEGIN
    UPDATE dbo.QUAL_CARD_IMPL SET ROUTE_SUPERVISOR = 0 WHERE ROUTE_SUPERVISOR IS NULL;
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'QUAL_CARD_IMPL' AND COLUMN_NAME = 'IS_DELETED')
BEGIN
    UPDATE dbo.QUAL_CARD_IMPL SET IS_DELETED = 0 WHERE IS_DELETED IS NULL;
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
           WHERE TABLE_NAME = 'QUAL_CARD_IMPL' AND COLUMN_NAME = 'IS_ACTIVE')
BEGIN
    UPDATE dbo.QUAL_CARD_IMPL SET IS_ACTIVE = 1 WHERE IS_ACTIVE IS NULL;
END
GO

-- ============================================================
-- SECTION 9: LS_QUAL_CARD data copy from QUAL_CARD_IMPL
-- ============================================================

Print '*** Section 9: LS_QUAL_CARD data population ***'
go

IF NOT EXISTS (SELECT TOP 1 1 FROM dbo.LS_QUAL_CARD)
BEGIN
    SET IDENTITY_INSERT dbo.LS_QUAL_CARD ON;

    INSERT INTO dbo.LS_QUAL_CARD (
        PK_LS_QUAL_CARD_ID, FK_LS_ID, FK_QUAL_CARD_IMPL_ID,
        DATE_CREATED, DATE_MODIFIED, FK_CREATED_BY, FK_MODIFIED_BY,
        IS_DELETED, DELETED_DATE, FK_DELETED_BY
    )
    SELECT
        PK_QUAL_CARD_IMPL_ID, FK_LS_ID, PK_QUAL_CARD_IMPL_ID,
        DATE_CREATED, DATE_MODIFIED, FK_CREATED_BY, FK_MODIFIED_BY,
        0, NULL, NULL
    FROM dbo.QUAL_CARD_IMPL
    WHERE FK_LS_ID IS NOT NULL;

    SET IDENTITY_INSERT dbo.LS_QUAL_CARD OFF;
END
GO

-- ============================================================
-- SECTION 10: FK relationships re-creation after data migration
-- ============================================================

Print '*** Section 10: Recreating FK constraints ***'
go

-- FK_EXAM_QUESTION_EVENT_IMPL_ID
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'FK_EXAM_QUESTION_EVENT_IMPL_ID')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT]
    ADD CONSTRAINT [FK_EXAM_QUESTION_EVENT_IMPL_ID]
    FOREIGN KEY ([FK_QUESTION_IMPL]) REFERENCES [dbo].[QUESTION_IMPL] ([PK_QUESTION_IMPL_ID]);
GO

-- FK_EXAM_QUESTION_EVENT_MC_IMPL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'FK_EXAM_QUESTION_EVENT_MC_IMPL')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT_MC]
    ADD CONSTRAINT [FK_EXAM_QUESTION_EVENT_MC_IMPL]
    FOREIGN KEY ([FK_QUESTION_IMPL]) REFERENCES [dbo].[QUESTION_IMPL] ([PK_QUESTION_IMPL_ID]);
GO

-- FK_EXAM_QUESTION_EVENT_MA_IMPL
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'FK_EXAM_QUESTION_EVENT_MA_IMPL')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT_MA]
    ADD CONSTRAINT [FK_EXAM_QUESTION_EVENT_MA_IMPL]
    FOREIGN KEY ([FK_QUESTION_IMPL]) REFERENCES [dbo].[QUESTION_IMPL] ([PK_QUESTION_IMPL_ID]);
GO

-- PK_EXAM_QUESTION_EVENT_MC
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'PK_EXAM_QUESTION_EVENT_MC')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT_MC] WITH NOCHECK
    ADD CONSTRAINT [PK_EXAM_QUESTION_EVENT_MC]
    PRIMARY KEY CLUSTERED ([PK_EXAM_QUESTION_EVENT_MC_ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
          IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

-- PK_EXAM_QUESTION_EVENT_MA
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'PK_EXAM_QUESTION_EVENT_MA')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT_MA] WITH NOCHECK
    ADD CONSTRAINT [PK_EXAM_QUESTION_EVENT_MA]
    PRIMARY KEY CLUSTERED ([PK_EXAM_QUESTION_EVENT_MA_ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
          IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

-- FK: EXAM_QUESTION_EVENT -> EXAM
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'FK_EXAM_QUESTION_EVENT_EXAM_ID')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT]
    ADD CONSTRAINT [FK_EXAM_QUESTION_EVENT_EXAM_ID]
    FOREIGN KEY ([FK_EXAM_ID]) REFERENCES [dbo].[EXAM] ([PK_EXAM_ID]);
GO

-- FK: EXAM_QUESTION_EVENT_MC -> EXAM
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'FK_EXAM_QUESTION_EVENT_MC_EXAM_ID')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT_MC]
    ADD CONSTRAINT [FK_EXAM_QUESTION_EVENT_MC_EXAM_ID]
    FOREIGN KEY ([FK_EXAM_ID]) REFERENCES [dbo].[EXAM] ([PK_EXAM_ID]);
GO

-- FK: EXAM_QUESTION_EVENT_MA -> EXAM
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'FK_EXAM_QUESTION_EVENT_MA_EXAM_ID')
    ALTER TABLE [dbo].[EXAM_QUESTION_EVENT_MA]
    ADD CONSTRAINT [FK_EXAM_QUESTION_EVENT_MA_EXAM_ID]
    FOREIGN KEY ([FK_EXAM_ID]) REFERENCES [dbo].[EXAM] ([PK_EXAM_ID]);
GO

-- ============================================================
-- SECTION 11: Additional performance indexes
-- ============================================================

Print '*** Section 11: Creating additional indexes ***'
go

IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.EXAM_QUESTION_EVENT_MC') AND name = 'NDX_EXAM_QUESTION_EVENT_MC1')
    CREATE NONCLUSTERED INDEX [NDX_EXAM_QUESTION_EVENT_MC1]
    ON [dbo].[EXAM_QUESTION_EVENT_MC] ([FK_EXAM_ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
          DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.EXAM_QUESTION_EVENT') AND name = 'NDX_EXAM_QUESTION_EVENT4')
    CREATE NONCLUSTERED INDEX [NDX_EXAM_QUESTION_EVENT4]
    ON [dbo].[EXAM_QUESTION_EVENT] ([FK_EXAM_ID] ASC, [FK_QUESTION_IMPL] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
          DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.EXAM_QUESTION_EVENT') AND name = 'NDX_EXAM_QUESTION_EVENT1')
    CREATE NONCLUSTERED INDEX [NDX_EXAM_QUESTION_EVENT1]
    ON [dbo].[EXAM_QUESTION_EVENT] ([FK_QUESTION_IMPL] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
          DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

-- Additional indexes for EXAM_QUESTION_EVENT_MA
IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.EXAM_QUESTION_EVENT_MA') AND name = 'NDX_EXAM_QUESTION_EVENT_MA1')
    CREATE NONCLUSTERED INDEX [NDX_EXAM_QUESTION_EVENT_MA1]
    ON [dbo].[EXAM_QUESTION_EVENT_MA] ([FK_EXAM_ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
          DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.EXAM_QUESTION_EVENT_MA') AND name = 'NDX_EXAM_QUESTION_EVENT_MA2')
    CREATE NONCLUSTERED INDEX [NDX_EXAM_QUESTION_EVENT_MA2]
    ON [dbo].[EXAM_QUESTION_EVENT_MA] ([FK_QUESTION_IMPL] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
          DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

-- OBJECTIVE_IMPL index for approved status lookups
IF NOT EXISTS (SELECT * FROM sys.indexes
               WHERE object_id = OBJECT_ID('dbo.OBJECTIVE_IMPL') AND name = 'NDX_OBJECTIVE_IMPL_APPROVED_STATUS')
    CREATE NONCLUSTERED INDEX [NDX_OBJECTIVE_IMPL_APPROVED_STATUS]
    ON [dbo].[OBJECTIVE_IMPL] ([APPROVED_STATUS] ASC, [FK_OBJ_ID] ASC)
    WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF,
          DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON);
GO

-- ============================================================
-- SECTION 12: LEARNER FK constraints
-- ============================================================

Print '*** Section 12: LEARNER FK constraints ***'
go

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'FK_LEARNER_FK_CREATED_BY')
    ALTER TABLE [dbo].[LEARNER]
    ADD CONSTRAINT [FK_LEARNER_FK_CREATED_BY]
    FOREIGN KEY ([FK_CREATED_BY]) REFERENCES [dbo].[FOCUS_USER] ([PK_FOCUS_USER_ID]);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'FK_LEARNER_FK_EXPIRED_BY')
    ALTER TABLE [dbo].[LEARNER]
    ADD CONSTRAINT [FK_LEARNER_FK_EXPIRED_BY]
    FOREIGN KEY ([FK_EXPIRED_BY]) REFERENCES [dbo].[FOCUS_USER] ([PK_FOCUS_USER_ID]);
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
               WHERE CONSTRAINT_NAME = 'FK_LEARNER_FK_MODIFIED_BY')
    ALTER TABLE [dbo].[LEARNER]
    ADD CONSTRAINT [FK_LEARNER_FK_MODIFIED_BY]
    FOREIGN KEY ([FK_MODIFIED_BY]) REFERENCES [dbo].[FOCUS_USER] ([PK_FOCUS_USER_ID]);
GO

-- ============================================================
-- SECTION 13: XREF_LIB default data population
-- ============================================================

Print '*** Section 13: XREF_LIB default data population ***'
go

-- Insert default XREF_LIB rows (idempotent via NOT EXISTS check)
IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'OBJECTIVE_STATUS' AND LIB_VALUE = 0)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('OBJECTIVE_STATUS', 0, 'Not Started', 1, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'OBJECTIVE_STATUS' AND LIB_VALUE = 1)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('OBJECTIVE_STATUS', 1, 'In Progress', 0, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'OBJECTIVE_STATUS' AND LIB_VALUE = 2)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('OBJECTIVE_STATUS', 2, 'Completed', 0, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'APPROVED_STATUS' AND LIB_VALUE = 0)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('APPROVED_STATUS', 0, 'Pending', 1, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'APPROVED_STATUS' AND LIB_VALUE = 1)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('APPROVED_STATUS', 1, 'Approved', 0, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'APPROVED_STATUS' AND LIB_VALUE = 2)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('APPROVED_STATUS', 2, 'Rejected', 0, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'QUAL_CARD_STATUS' AND LIB_VALUE = 0)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('QUAL_CARD_STATUS', 0, 'Open', 1, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'QUAL_CARD_STATUS' AND LIB_VALUE = 1)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('QUAL_CARD_STATUS', 1, 'Submitted', 0, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'QUAL_CARD_STATUS' AND LIB_VALUE = 2)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('QUAL_CARD_STATUS', 2, 'Approved', 0, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'QUAL_CARD_STATUS' AND LIB_VALUE = 3)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('QUAL_CARD_STATUS', 3, 'Rejected', 0, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'EXAM_RESULT_STATUS' AND LIB_VALUE = 0)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('EXAM_RESULT_STATUS', 0, 'In Progress', 1, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'EXAM_RESULT_STATUS' AND LIB_VALUE = 1)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('EXAM_RESULT_STATUS', 1, 'Pass', 0, 1);
END
GO

IF NOT EXISTS (SELECT * FROM dbo.XREF_LIB WHERE LIB_TYPE = 'EXAM_RESULT_STATUS' AND LIB_VALUE = 2)
BEGIN
    INSERT INTO dbo.XREF_LIB (LIB_TYPE, LIB_VALUE, LIB_LABEL, IS_DEFAULT, IS_ACTIVE)
    VALUES ('EXAM_RESULT_STATUS', 2, 'Fail', 0, 1);
END
GO

-- ============================================================
-- SECTION 14: XREF_LIB_IMPL cursor block
-- ============================================================

Print '*** Section 14: XREF_LIB_IMPL default row population ***'
go

DECLARE @PK_LIB_ID NUMERIC(12,0)
DECLARE @CHECK INT

DECLARE LIB_CURSOR CURSOR FOR
    SELECT PK_XREF_LIB_ID FROM dbo.XREF_LIB

OPEN LIB_CURSOR
FETCH NEXT FROM LIB_CURSOR INTO @PK_LIB_ID

WHILE @@FETCH_STATUS = 0
BEGIN
    SELECT @CHECK = COUNT(*) FROM dbo.XREF_LIB_IMPL WHERE FK_XREF_LIB_ID = @PK_LIB_ID

    if @CHECK = 0 BEGIN
        INSERT INTO dbo.XREF_LIB_IMPL (FK_XREF_LIB_ID, IS_ACTIVE, DATE_CREATED, DATE_MODIFIED)
        VALUES (@PK_LIB_ID, 1, GETDATE(), GETDATE())
    END

    FETCH NEXT FROM LIB_CURSOR INTO @PK_LIB_ID
END

CLOSE LIB_CURSOR
DEALLOCATE LIB_CURSOR
go

-- ============================================================
-- SECTION 15: LS_RULE_ITEMS schema changes
-- ============================================================

Print '*** Section 15: LS_RULE_ITEMS schema changes ***'
go

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LS_RULE_ITEMS')
BEGIN
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
                   WHERE TABLE_NAME = 'LS_RULE_ITEMS' AND COLUMN_NAME = 'RULE_WEIGHT')
        ALTER TABLE dbo.LS_RULE_ITEMS ADD RULE_WEIGHT NUMERIC(5,2) NULL;
END
GO

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LS_RULE_ITEMS')
BEGIN
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
                   WHERE TABLE_NAME = 'LS_RULE_ITEMS' AND COLUMN_NAME = 'IS_MANDATORY')
        ALTER TABLE dbo.LS_RULE_ITEMS ADD IS_MANDATORY BIT NOT NULL CONSTRAINT DF_LS_RULE_ITEMS_IS_MANDATORY DEFAULT 0;
END
GO

IF EXISTS (SELECT * FROM sys.tables WHERE name = 'LS_RULE_ITEMS')
BEGIN
    IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS
                   WHERE TABLE_NAME = 'LS_RULE_ITEMS' AND COLUMN_NAME = 'SORT_ORDER')
        ALTER TABLE dbo.LS_RULE_ITEMS ADD SORT_ORDER INT NULL;
END
GO

-- ============================================================
-- SECTION 16: DB_UPDATE_HISTORY version record
-- ============================================================

Print '*** Section 16: Recording DB_UPDATE_HISTORY ***'
go

INSERT INTO dbo.DB_UPDATE_HISTORY (UPDATE_NAME, UPDATE_VERSION, DATE_APPLIED, APPLIED_BY)
VALUES ('VISION-MSSQL-8.6-9.0.2-NoVLS Part 2', '9.0.2', GETDATE(), SYSTEM_USER)
go

-- ============================================================
-- SECTION 17: GRANT statements
-- ============================================================

Print '*** Section 17: Applying permission grants ***'
go

IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'VisionApp' AND type IN ('S','U','G'))
BEGIN
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.XREF_LIB         TO VisionApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.XREF_LIB_IMPL    TO VisionApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.LS_QUAL_CARD      TO VisionApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.OBJECTIVE_IMPL    TO VisionApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.EXAM_QUESTION_EVENT    TO VisionApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.EXAM_QUESTION_EVENT_MC TO VisionApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.EXAM_QUESTION_EVENT_MA TO VisionApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.QUAL_CARD_IMPL    TO VisionApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.LEARNER           TO VisionApp;
    GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.DB_UPDATE_HISTORY TO VisionApp;
END
GO

IF EXISTS (SELECT * FROM sys.database_principals WHERE name = 'VisionReadOnly' AND type IN ('S','U','G'))
BEGIN
    GRANT SELECT ON dbo.XREF_LIB              TO VisionReadOnly;
    GRANT SELECT ON dbo.XREF_LIB_IMPL         TO VisionReadOnly;
    GRANT SELECT ON dbo.LS_QUAL_CARD           TO VisionReadOnly;
    GRANT SELECT ON dbo.OBJECTIVE_IMPL         TO VisionReadOnly;
    GRANT SELECT ON dbo.EXAM_QUESTION_EVENT    TO VisionReadOnly;
    GRANT SELECT ON dbo.EXAM_QUESTION_EVENT_MC TO VisionReadOnly;
    GRANT SELECT ON dbo.EXAM_QUESTION_EVENT_MA TO VisionReadOnly;
    GRANT SELECT ON dbo.QUAL_CARD_IMPL         TO VisionReadOnly;
    GRANT SELECT ON dbo.DB_UPDATE_HISTORY      TO VisionReadOnly;
END
GO

Print '*** VISION-MSSQL 8.6 -> 9.0.2 Part 2a upgrade script complete ***'
go
